# Site settings
name: syareez's blog
email: muhammadsyareez@gmail.com
author: Syareez Zainal
url: http://syareez.github.io
resume_site: http://syareez.github.io/
github: https://github.com/syareez/
baseurl: ""
description: welcome to my personal-blog-cum-personal-website
meta_description: welcome to my personal-blog-cum-personal-website
motto: It's our wits that make us men.
banner: whateven is a banner

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: syareez

# Build settings
markdown: kramdown
